# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4dacd455da261c5467a0205994dfc4e8b26d286bb8608b35b83a4f22cc93bdf17bb747c7000d0e769dea53f68accc1fa8739c110259a3d568ad323fa7cfe11f

test:
  secret_key_base: 867e05b89841ca2f37f75c74de936197d4a4b0a6e5cf1bc920999f83d70d9b17780094b5df7bfa9a37c954def676f7d94a3f42bbde1144925e86c31a30b1572e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
